name: Maven CI for 1Password Connect Jenkins Plugin
on:
  push:
    branches: main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      OP_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
      OP_SA_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Launch 1Password Connect instance
        env:
          OP_CONNECT_CREDENTIALS: ${{ secrets.OP_CONNECT_CREDENTIALS }}
        run: |
          echo "$OP_CONNECT_CREDENTIALS" > 1password-credentials.json
          docker-compose -f tests/fixtures/docker-compose.yml up -d && sleep 10
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -q --batch-mode --update-snapshots verify
